name: hwddda-environment
channels:
  - bokeh/label/dev
dependencies:
  - python
  - bokeh
  - pyviz_comms
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - matplotlib
    - pyct
    - numpy
    - pandas
    - vectormath
    - panel
